// forge/templates/apps/svelte-frontend-template/template/src/lib/features/chat/ui/AiChat.svelte
<script lang="ts">
	import { MessageCircle, RefreshCw, X } from 'lucide-svelte';
	import { getUiStore } from '$lib/features/shell';
	import { getChatStore } from '$lib/features/chat';
	import { APPROVAL_MODES, AVAILABLE_MODELS } from '../chat.constants';
	import AgentStatusBar from './AgentStatusBar.svelte';
	import AiChatInput from './AiChatInput.svelte';
	import AiChatMessage from './AiChatMessage.svelte';
	import UserPromptCard from './UserPromptCard.svelte';
	import type { ChatMode } from '$lib/features/shell';

	let { mode = 'inline' }: { mode?: ChatMode } = $props();

	const ui = getUiStore();
	const chat = getChatStore();

	let messagesContainer: HTMLDivElement | undefined;
	let chatInputRef: AiChatInput | undefined;

	$effect(() => {
		const _ = chat.messages.length;
		if (messagesContainer) {
			requestAnimationFrame(() => {
				if (messagesContainer) {
					messagesContainer.scrollTop = messagesContainer.scrollHeight;
				}
			});
		}
	});

	$effect(() => {
		if (ui.chatOpen && chatInputRef) {
			setTimeout(() => chatInputRef?.focusInput(), 350);
		}
	});

	function handlePanelKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			e.preventDefault();
			ui.closeChat();
		}
	}
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<aside
	id="ai-chat-panel"
	class="flex h-full flex-col bg-background border-ai-border"
	aria-label="AI Chat"
	onkeydown={handlePanelKeydown}
	data-testid="ai-chat-panel"
>
	<!-- Header -->
	<div class="flex h-14 shrink-0 items-center justify-between gap-2 border-b border-ai-border px-3">
		<div class="flex min-w-0 items-center gap-2">
			<MessageCircle class="h-4 w-4 shrink-0 text-ai-accent" aria-hidden="true" />
			<select
				class="rounded border border-input bg-background px-1.5 py-0.5 text-xs font-medium focus:outline-none"
				value={chat.model}
				onchange={(e) => chat.setModel(e.currentTarget.value as typeof chat.model)}
				aria-label="Model"
				data-testid="model-select"
			>
				{#each AVAILABLE_MODELS as m (m.id)}
					<option value={m.id}>{m.label}</option>
				{/each}
			</select>
			<select
				class="rounded border border-input bg-background px-1.5 py-0.5 text-xs focus:outline-none"
				value={chat.approvalMode}
				onchange={(e) => chat.setApprovalMode(e.currentTarget.value as typeof chat.approvalMode)}
				aria-label="Approval mode"
				data-testid="approval-select"
			>
				{#each APPROVAL_MODES as a (a.id)}
					<option value={a.id}>{a.label}</option>
				{/each}
			</select>
		</div>
		<div class="flex items-center gap-1">
			<span
				class="hidden rounded-full bg-ai-surface px-2.5 py-0.5 text-xs text-ai-surface-foreground sm:inline"
			>
				{chat.contextLabel}
			</span>
			<button
				class="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
				onclick={() => chat.clearMessages()}
				aria-label="New thread"
				title="New thread"
				data-testid="new-thread-button"
			>
				<RefreshCw class="h-4 w-4" />
			</button>
			<button
				class="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
				onclick={() => ui.closeChat()}
				aria-label="Close AI Chat"
			>
				<X class="h-4 w-4" />
			</button>
		</div>
	</div>

	<!-- Messages -->
	<div
		bind:this={messagesContainer}
		class="flex-1 space-y-4 overflow-y-auto p-4"
		data-testid="messages-list"
	>
		{#if chat.messages.length === 0}
			<div class="flex h-full flex-col items-center justify-center px-6 text-center">
				<div class="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-ai-surface">
					<MessageCircle class="h-6 w-6 text-ai-accent" />
				</div>
				<h3 class="mb-1 text-sm font-medium">How can I help?</h3>
				<p class="text-xs text-muted-foreground">
					Ask a question or describe what you need help with.
				</p>
			</div>
		{:else}
			{#each chat.messages as message, idx (message.id)}
				<AiChatMessage
					{message}
					toolCalls={idx === chat.messages.length - 1 ? chat.activeToolCalls : []}
					onRegenerate={!chat.isGenerating &&
					message.role === 'assistant' &&
					idx === chat.messages.length - 1
						? chat.regenerate
						: undefined}
				/>
			{/each}
			{#if chat.pendingPrompt}
				<UserPromptCard prompt={chat.pendingPrompt} onRespond={chat.respondToPrompt} />
			{/if}
			{#if chat.error}
				<div
					class="flex items-center gap-2 rounded-md border border-red-500/40 bg-red-50 p-2 text-xs text-red-700 dark:bg-red-950/40 dark:text-red-300"
					data-testid="chat-error"
				>
					<span class="min-w-0 flex-1 truncate">{chat.error.message}</span>
					<button
						class="shrink-0 underline"
						onclick={() => chat.retryLastRun()}
						data-testid="chat-error-retry"
					>
						Retry
					</button>
					<button
						class="shrink-0 underline"
						onclick={() => chat.dismissError()}
						data-testid="chat-error-dismiss"
					>
						Dismiss
					</button>
				</div>
			{/if}
			{#if chat.isGenerating}
				<div class="flex items-center gap-2 text-xs text-muted-foreground">
					<div class="flex gap-1">
						<span
							class="h-1.5 w-1.5 animate-bounce rounded-full bg-ai-accent [animation-delay:0ms]"
						></span>
						<span
							class="h-1.5 w-1.5 animate-bounce rounded-full bg-ai-accent [animation-delay:150ms]"
						></span>
						<span
							class="h-1.5 w-1.5 animate-bounce rounded-full bg-ai-accent [animation-delay:300ms]"
						></span>
					</div>
					<span>Thinking...</span>
				</div>
			{/if}
		{/if}
	</div>

	<AgentStatusBar state={chat.customState} />

	<!-- Input -->
	<AiChatInput bind:this={chatInputRef} />
</aside>

// forge/templates/apps/vue-frontend-template/template/src/features/ai_chat/ui/AiChat.vue
<script setup lang="ts">
import { ref, computed, nextTick, watch } from 'vue'
import { useRoute } from 'vue-router'
import {
  X, Sparkles, Plus, Code2, ArrowUp, SlidersHorizontal, Monitor, ShieldCheck,
  ChevronDown, MessageSquarePlus, Settings, Maximize2,
} from 'lucide-vue-next'
import { Button } from '@/shared/ui/button'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from '@/shared/ui/dropdown-menu'
import {
  TooltipProvider,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
} from '@/shared/ui/tooltip'
import { AlertCircle } from 'lucide-vue-next'
import { useAiChat } from '../composables/useAiChat'
import AiChatMessage from './AiChatMessage.vue'
import UserPromptCard from './UserPromptCard.vue'

const MODEL_OPTIONS = [
  { value: 'openai:gpt-4.1', label: 'GPT-4.1' },
  { value: 'openai:gpt-4.1-mini', label: 'GPT-4.1 Mini' },
  { value: 'anthropic:claude-sonnet-4-20250514', label: 'Claude Sonnet 4' },
]

const route = useRoute()
const {
  messages,
  isGenerating,
  chatContext,
  pendingPrompt,
  runError,
  closeChat,
  sendMessage,
  respondToPrompt,
  editAndResend,
  clearMessages,
} = useAiChat()

function dismissError() {
  runError.value = null
}

const inputText = ref('')
const selectedModel = ref('openai:gpt-4.1')
const approvalMode = ref<'default' | 'bypass'>('default')
const messagesContainer = ref<HTMLElement | null>(null)
const textareaEl = ref<HTMLTextAreaElement | null>(null)
const chatPanel = ref<HTMLElement | null>(null)

const modelLabel = computed(() =>
  MODEL_OPTIONS.find(m => m.value === selectedModel.value)?.label ?? selectedModel.value,
)

const lastMessageIsAssistant = computed(() => {
  const msgs = messages.value
  return msgs.length > 0 && msgs[msgs.length - 1].role === 'assistant'
})

watch(
  () => route.meta.title,
  (title) => {
    chatContext.value = (title as string) || 'Current Page'
  },
  { immediate: true },
)

function autoResize() {
  const el = textareaEl.value
  if (!el) return
  // Collapse to 0 to get true scrollHeight independent of current height
  el.style.height = '0'
  const scrollH = el.scrollHeight
  const minH = 56 // ~2 lines + padding
  const panelH = chatPanel.value?.clientHeight ?? window.innerHeight
  const maxH = Math.floor(panelH * 0.5)
  const targetH = Math.max(minH, Math.min(scrollH, maxH))
  el.style.height = `${targetH}px`
  el.style.overflowY = scrollH > maxH ? 'auto' : 'hidden'
}

function handleSend() {
  const text = inputText.value.trim()
  if (!text || isGenerating.value) return
  sendMessage(text, { model: selectedModel.value, approval: approvalMode.value })
  inputText.value = ''
  nextTick(() => {
    if (textareaEl.value) {
      textareaEl.value.style.height = ''
      textareaEl.value.style.overflowY = 'hidden'
    }
    scrollToBottom()
  })
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  } else if (e.key === 'Enter' && e.shiftKey) {
    // Shift+Enter adds newline — resize on next tick after the newline is inserted
    nextTick(autoResize)
  }
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
  }
}

watch(messages, () => nextTick(scrollToBottom), { deep: true })
</script>

<template>
  <aside ref="chatPanel" class="flex h-full flex-col bg-background">
    <!-- Header -->
    <div class="flex h-14 shrink-0 items-center justify-between border-b px-4">
      <div class="flex items-center gap-2">
        <div class="flex h-7 w-7 items-center justify-center rounded-full ai-gradient">
          <Sparkles class="h-3.5 w-3.5 text-white" />
        </div>
        <span class="text-sm font-medium">AI Assistant</span>
      </div>

      <div class="flex items-center gap-0.5">
        <TooltipProvider :delay-duration="300">
          <Tooltip>
            <TooltipTrigger as-child>
              <Button variant="ghost" size="icon" class="h-8 w-8 text-muted-foreground" @click="clearMessages">
                <MessageSquarePlus class="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">New Chat</TooltipContent>
          </Tooltip>
        </TooltipProvider>

        <TooltipProvider :delay-duration="300">
          <Tooltip>
            <TooltipTrigger as-child>
              <Button variant="ghost" size="icon" class="h-8 w-8 text-muted-foreground">
                <Settings class="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">Settings</TooltipContent>
          </Tooltip>
        </TooltipProvider>

        <TooltipProvider :delay-duration="300">
          <Tooltip>
            <TooltipTrigger as-child>
              <Button variant="ghost" size="icon" class="h-8 w-8 text-muted-foreground">
                <Maximize2 class="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">Maximize</TooltipContent>
          </Tooltip>
        </TooltipProvider>

        <div class="mx-1 h-5 w-px bg-border" />

        <Button variant="ghost" size="icon" class="h-8 w-8 interactive-press" @click="closeChat">
          <X class="h-4 w-4" />
        </Button>
      </div>
    </div>

    <!-- Messages -->
    <div
      ref="messagesContainer"
      role="log"
      aria-label="Chat messages"
      class="flex flex-1 flex-col gap-4 overflow-y-auto scrollbar-thin p-4"
    >
      <div
        v-if="messages.length === 0 && !isGenerating"
        class="flex flex-1 flex-col items-center justify-center gap-3 text-center"
      >
        <div class="flex h-16 w-16 items-center justify-center rounded-full ai-gradient">
          <Sparkles class="h-8 w-8 text-white" />
        </div>
        <p class="text-sm text-muted-foreground">Ask me anything about this page.</p>
      </div>

      <AiChatMessage
        v-for="(msg, idx) in messages"
        :key="msg.id"
        :message="msg"
        :is-streaming="isGenerating && msg.role === 'assistant' && idx === messages.length - 1"
        @edit="(payload) => editAndResend(payload.id, payload.content, { model: selectedModel, approval: approvalMode })"
      />

      <!-- Thinking indicator -->
      <div
        v-if="isGenerating && !lastMessageIsAssistant"
        class="flex items-center gap-2"
      >
        <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full ai-gradient ai-glow transition-shadow">
          <Sparkles class="h-3.5 w-3.5 text-white" />
        </div>
        <span class="text-xs text-muted-foreground animate-pulse">Thinking...</span>
      </div>

      <!-- HITL prompt card -->
      <UserPromptCard
        v-if="pendingPrompt && !isGenerating"
        :prompt="pendingPrompt"
        :disabled="isGenerating"
        @respond="respondToPrompt"
      />
    </div>

    <!-- Error banner -->
    <div v-if="runError" class="flex items-center gap-2 border-t bg-destructive/10 px-3 py-2 text-sm text-destructive">
      <AlertCircle class="h-4 w-4 shrink-0" />
      <span class="flex-1 truncate">{{ runError.message }}</span>
      <button class="shrink-0 text-xs underline" @click="dismissError">Dismiss</button>
    </div>

    <!-- Input area -->
    <div class="border-t p-3">
      <div
        class="flex flex-col rounded-lg border bg-card transition-shadow"
        :class="{ 'ai-pulse': isGenerating }"
      >
        <textarea
          ref="textareaEl"
          v-model="inputText"
          placeholder="Describe what to build"
          aria-label="Chat message input"
          rows="2"
          class="resize-none bg-transparent px-4 pt-3 pb-1 text-sm outline-none placeholder:text-muted-foreground scrollbar-thin"
          @keydown="handleKeydown"
          @input="autoResize"
        />

        <!-- Toolbar row -->
        <div class="flex items-center gap-1 px-2 pb-2">
          <TooltipProvider :delay-duration="300">
            <Tooltip>
              <TooltipTrigger as-child>
                <Button variant="ghost" size="icon" class="h-7 w-7 text-muted-foreground">
                  <Plus class="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="top">Attach file</TooltipContent>
            </Tooltip>
          </TooltipProvider>

          <div class="flex items-center gap-1 rounded-md px-2 py-1 text-xs text-muted-foreground">
            <Code2 class="h-3.5 w-3.5" />
            <span>Agent</span>
          </div>

          <DropdownMenu>
            <DropdownMenuTrigger as-child>
              <button class="flex items-center gap-1 rounded-md px-2 py-1 text-xs text-muted-foreground hover:bg-accent hover:text-foreground transition-colors">
                {{ modelLabel }}
                <ChevronDown class="h-3 w-3" />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" side="top">
              <DropdownMenuItem
                v-for="opt in MODEL_OPTIONS"
                :key="opt.value"
                @click="selectedModel = opt.value"
              >
                {{ opt.label }}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <TooltipProvider :delay-duration="300">
            <Tooltip>
              <TooltipTrigger as-child>
                <Button variant="ghost" size="icon" class="h-7 w-7 text-muted-foreground">
                  <SlidersHorizontal class="h-3.5 w-3.5" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="top">Settings</TooltipContent>
            </Tooltip>
          </TooltipProvider>

          <div class="flex-1" />

          <Button
            variant="ghost"
            size="icon"
            class="h-7 w-7 shrink-0 rounded-full border border-border interactive-press"
            :disabled="!inputText.trim() || isGenerating"
            @click="handleSend"
          >
            <ArrowUp class="h-3.5 w-3.5 text-ai-from" />
          </Button>
        </div>
      </div>

      <!-- Session context row -->
      <div class="flex items-center gap-3 px-2 pt-2 text-[11px] text-muted-foreground">
        <div class="flex items-center gap-1">
          <Monitor class="h-3 w-3" />
          <span>Local</span>
        </div>

        <DropdownMenu>
          <DropdownMenuTrigger as-child>
            <button class="flex items-center gap-1 hover:text-foreground transition-colors">
              <ShieldCheck class="h-3 w-3" />
              <span>{{ approvalMode === 'default' ? 'Default Approvals' : 'Bypass Approvals' }}</span>
              <ChevronDown class="h-2.5 w-2.5" />
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start" side="top">
            <DropdownMenuItem @click="approvalMode = 'default'">
              Default Approvals
            </DropdownMenuItem>
            <DropdownMenuItem @click="approvalMode = 'bypass'">
              Bypass Approvals
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </div>
  </aside>
</template>
