// forge/templates/apps/vue-frontend-template/template/src/features/ai_chat/canvas/DataTable.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { ArrowUp, ArrowDown, Search } from 'lucide-vue-next'
import { Input } from '@/shared/ui/input'
import { Button } from '@/shared/ui/button'
import type { WorkspaceActivity, AgentState } from '../types'

const props = defineProps<{
  activity: WorkspaceActivity
  state?: AgentState
}>()

defineEmits<{
  action: [action: { type: string; data: Record<string, any> }]
}>()

const schema = computed(() => props.activity.content.props || props.activity.content)
const columns = computed(() => schema.value.columns || [])
const allRows = computed(() => schema.value.rows || [])
const pageSize = computed(() => schema.value.pageSize || 25)

const sortKey = ref(schema.value.defaultSort?.key || '')
const sortDir = ref<'asc' | 'desc'>(schema.value.defaultSort?.direction || 'asc')
const filterText = ref('')
const currentPage = ref(1)
const selectedIds = ref<Set<number | string>>(new Set())

const filteredRows = computed(() => {
  if (!filterText.value) return allRows.value
  const q = filterText.value.toLowerCase()
  return allRows.value.filter((row: any) =>
    columns.value.some((col: any) => {
      const val = row[col.key]
      return val !== null && val !== undefined && String(val).toLowerCase().includes(q)
    }),
  )
})

const sortedRows = computed(() => {
  if (!sortKey.value) return filteredRows.value
  const key = sortKey.value
  const dir = sortDir.value === 'asc' ? 1 : -1
  return [...filteredRows.value].sort((a: any, b: any) => {
    const av = a[key] ?? ''
    const bv = b[key] ?? ''
    if (typeof av === 'number' && typeof bv === 'number') return (av - bv) * dir
    return String(av).localeCompare(String(bv)) * dir
  })
})

const totalPages = computed(() => Math.max(1, Math.ceil(sortedRows.value.length / pageSize.value)))
const pagedRows = computed(() => {
  const start = (currentPage.value - 1) * pageSize.value
  return sortedRows.value.slice(start, start + pageSize.value)
})

function toggleSort(key: string) {
  if (sortKey.value === key) {
    sortDir.value = sortDir.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortKey.value = key
    sortDir.value = 'asc'
  }
  currentPage.value = 1
}

function toggleSelect(id: number | string) {
  const s = new Set(selectedIds.value)
  if (s.has(id)) s.delete(id)
  else s.add(id)
  selectedIds.value = s
}

function formatCell(value: any, col: any): string {
  if (value === null || value === undefined || value === '') return '—'
  if (col.format === 'duration') {
    if (value === 0) return '—'
    return value < 1000 ? `${value}ms` : `${(value / 1000).toFixed(1)}s`
  }
  if (col.type === 'date') {
    if (!value) return '—'
    try { return new Date(value).toLocaleString() } catch { return String(value) }
  }
  if (col.truncate && String(value).length > col.truncate) {
    return String(value).slice(0, col.truncate) + '...'
  }
  return String(value)
}

const badgeColors: Record<string, string> = {
  completed: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  running: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
  pending: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  failed: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  skipped: 'bg-gray-100 text-gray-400 dark:bg-gray-800 dark:text-gray-500',
}
</script>

<template>
  <div class="flex h-full flex-col p-4">
    <div class="mb-4 flex items-center justify-between">
      <h2 class="text-lg font-semibold">{{ schema.title }}</h2>
      <div class="relative w-64">
        <Search class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
        <Input v-model="filterText" placeholder="Filter..." class="pl-8 h-9 text-sm" />
      </div>
    </div>

    <div class="flex-1 overflow-auto rounded-lg border">
      <table class="w-full text-sm">
        <thead class="sticky top-0 z-10 bg-muted/80 backdrop-blur">
          <tr>
            <th v-if="schema.selectable" class="w-10 px-3 py-2" />
            <th
              v-for="col in columns"
              :key="col.key"
              class="px-3 py-2 text-left font-medium text-muted-foreground"
              :class="col.sortable ? 'cursor-pointer select-none hover:text-foreground' : ''"
              @click="col.sortable && toggleSort(col.key)"
            >
              <div class="flex items-center gap-1">
                {{ col.label }}
                <template v-if="col.sortable && sortKey === col.key">
                  <ArrowUp v-if="sortDir === 'asc'" class="h-3 w-3" />
                  <ArrowDown v-else class="h-3 w-3" />
                </template>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="row in pagedRows"
            :key="row.id"
            class="border-t transition-colors hover:bg-muted/50"
            :class="selectedIds.has(row.id) ? 'bg-primary/5' : ''"
          >
            <td v-if="schema.selectable" class="px-3 py-2">
              <input
                type="checkbox"
                :checked="selectedIds.has(row.id)"
                class="h-4 w-4 rounded border-input"
                @change="toggleSelect(row.id)"
              />
            </td>
            <td v-for="col in columns" :key="col.key" class="px-3 py-2">
              <span
                v-if="col.type === 'badge'"
                class="inline-flex rounded-full px-2 py-0.5 text-xs font-medium"
                :class="badgeColors[row[col.key]] || badgeColors.pending"
              >
                {{ row[col.key] }}
              </span>
              <span v-else>{{ formatCell(row[col.key], col) }}</span>
            </td>
          </tr>
          <tr v-if="pagedRows.length === 0">
            <td :colspan="columns.length + (schema.selectable ? 1 : 0)" class="px-3 py-8 text-center text-muted-foreground">
              No matching rows
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="mt-3 flex items-center justify-between text-xs text-muted-foreground">
      <span>{{ filteredRows.length }} rows{{ selectedIds.size ? ` · ${selectedIds.size} selected` : '' }}</span>
      <div class="flex items-center gap-2">
        <Button variant="outline" size="sm" :disabled="currentPage <= 1" class="h-7 text-xs" @click="currentPage--">Prev</Button>
        <span>{{ currentPage }} / {{ totalPages }}</span>
        <Button variant="outline" size="sm" :disabled="currentPage >= totalPages" class="h-7 text-xs" @click="currentPage++">Next</Button>
      </div>
    </div>
  </div>
</template>

// packages/canvas-svelte/src/components/DataTable.svelte
<!--
  DataTable canvas component — Svelte 5 variant.
-->
<script lang="ts">
  import type { DataTableProps } from '../generated/props'

  // The generated `DataTableProps` is the single source of truth —
  // hand-written mirror interfaces for canvas-component props are
  // banned by convention. `Column` extracts the element shape for the
  // `toggleSort` helper below.
  type Column = DataTableProps['columns'][number]

  let { columns, rows, pageSize = 25 }: DataTableProps = $props()

  let sortKey = $state<string | null>(null)
  let sortDir = $state<'asc' | 'desc'>('asc')
  let page = $state(0)

  function toggleSort(column: Column) {
    if (!column.sortable) return
    if (sortKey === column.key) {
      sortDir = sortDir === 'asc' ? 'desc' : 'asc'
    } else {
      sortKey = column.key
      sortDir = 'asc'
    }
  }

  let sortedRows = $derived.by(() => {
    const out = [...rows]
    if (sortKey) {
      const key = sortKey
      out.sort((a, b) => {
        const av = a[key]
        const bv = b[key]
        if (av == null) return 1
        if (bv == null) return -1
        if (av < bv) return sortDir === 'asc' ? -1 : 1
        if (av > bv) return sortDir === 'asc' ? 1 : -1
        return 0
      })
    }
    return out
  })

  let totalPages = $derived(Math.max(1, Math.ceil(sortedRows.length / pageSize)))
  let pagedRows = $derived(sortedRows.slice(page * pageSize, (page + 1) * pageSize))

  function goTo(p: number) {
    page = Math.max(0, Math.min(totalPages - 1, p))
  }

  function formatCell(value: unknown): string {
    if (value === null || value === undefined) return ''
    if (typeof value === 'object') return JSON.stringify(value)
    return String(value)
  }
</script>

<div class="forge-canvas-table">
  <table>
    <thead>
      <tr>
        {#each columns as col (col.key)}
          <th class:is-sortable={col.sortable} onclick={() => toggleSort(col)}>
            {col.label}
            {#if col.sortable}
              <span class="forge-canvas-table__sort" data-dir={sortKey === col.key ? sortDir : ''}>
                {sortKey === col.key ? (sortDir === 'asc' ? '▲' : '▼') : '↕'}
              </span>
            {/if}
          </th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each pagedRows as row, i (i)}
        <tr>
          {#each columns as col (col.key)}
            <td>{formatCell(row[col.key])}</td>
          {/each}
        </tr>
      {:else}
        <tr>
          <td class="forge-canvas-table__empty" colspan={columns.length}>No rows.</td>
        </tr>
      {/each}
    </tbody>
  </table>
  {#if totalPages > 1}
    <footer class="forge-canvas-table__footer">
      <button type="button" disabled={page === 0} onclick={() => goTo(page - 1)}>← Prev</button>
      <span>Page {page + 1} / {totalPages}</span>
      <button type="button" disabled={page >= totalPages - 1} onclick={() => goTo(page + 1)}>Next →</button>
    </footer>
  {/if}
</div>

<style>
  .forge-canvas-table { background: var(--fc-surface, #fff); border: 1px solid var(--fc-border, #e5e7eb); border-radius: 0.5rem; overflow: hidden; }
  table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
  th, td { padding: 0.625rem 0.75rem; text-align: left; border-bottom: 1px solid var(--fc-border, #e5e7eb); }
  th { background: var(--fc-muted, #f9fafb); font-weight: 600; user-select: none; }
  th.is-sortable { cursor: pointer; }
  th.is-sortable:hover { background: #f3f4f6; }
  .forge-canvas-table__sort { margin-left: 0.25rem; font-size: 0.75rem; color: #9ca3af; }
  .forge-canvas-table__sort[data-dir] { color: var(--fc-primary, #2563eb); }
  .forge-canvas-table__empty { text-align: center; color: #6b7280; padding: 2rem; }
  .forge-canvas-table__footer { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: 0.5rem 0.75rem; background: var(--fc-muted, #f9fafb); border-top: 1px solid var(--fc-border, #e5e7eb); font-size: 0.8rem; }
  .forge-canvas-table__footer button { padding: 0.25rem 0.625rem; border: 1px solid var(--fc-border, #e5e7eb); background: var(--fc-surface, #fff); border-radius: 0.25rem; cursor: pointer; }
  .forge-canvas-table__footer button:disabled { opacity: 0.4; cursor: not-allowed; }
</style>
