// forge/templates/layouts/svelte/tabbar/template/src/lib/features/shell/ui/NavRail.svelte
<script lang="ts">
	import type { Component } from 'svelte';
	import { page } from '$app/state';
	import { Settings, LogOut, UserCircle } from '@lucide/svelte';
	import { Popover } from 'bits-ui';
	import { getAuth } from '#lib/core/auth/auth.svelte.ts';

	interface RailItem {
		title: string;
		url: string;
		icon: Component;
	}

	let { items }: { items: RailItem[] } = $props();

	const auth = getAuth();

	function isActive(url: string) {
		if (url === '/') return page.url.pathname === '/';
		return page.url.pathname.startsWith(url);
	}

	const userInitials = $derived(
		auth.user
			? ((auth.user.firstName?.[0] ?? '') + (auth.user.lastName?.[0] ?? '')).toUpperCase() ||
					auth.user.username[0]?.toUpperCase() ||
					'?'
			: '?'
	);
</script>

<!--
	Slim icon-only nav rail (medium tier). Mirrors AppSidebar's primary-nav
	contract but in a 72px-wide icon column; the brand mark sits on top, the
	account popover anchors the bottom.
-->
<aside
	class="flex w-[72px] shrink-0 flex-col items-center border-r bg-sidebar-background text-sidebar-foreground"
>
	<!-- Brand mark -->
	<div class="flex h-14 w-full shrink-0 items-center justify-center border-b">
		<span
			class="flex h-8 w-8 items-center justify-center rounded-lg"
			style="background: linear-gradient(135deg, hsl(var(--ai-gradient-from)), hsl(var(--ai-gradient-to)))"
		>
			<span class="text-sm font-bold text-white">S</span>
		</span>
	</div>

	<!-- Icon-only primary nav -->
	<nav class="flex flex-1 flex-col items-center gap-1 overflow-y-auto py-3 px-2" aria-label="Primary navigation">
		{#each items as item}
			<a
				href={item.url}
				title={item.title}
				aria-current={isActive(item.url) ? 'page' : undefined}
				class="btn-press group relative flex h-10 w-12 items-center justify-center rounded-xl transition-colors
					{isActive(item.url) ? 'bg-sidebar-accent text-sidebar-accent-foreground' : 'text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground'}"
			>
				{#if isActive(item.url)}
					<span class="absolute left-0 top-1/2 -translate-y-1/2 h-5 w-[3px] rounded-r bg-primary"></span>
				{/if}
				<item.icon class="h-5 w-5" />
			</a>
		{/each}
	</nav>

	<!-- Account popover at bottom -->
	<div class="shrink-0 border-t py-2 px-2">
		<Popover.Root>
			<Popover.Trigger
				class="btn-press flex h-12 w-12 items-center justify-center rounded-xl transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
				title="Account"
				aria-label="Account menu"
			>
				<span
					class="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-xs font-medium"
				>
					{userInitials}
				</span>
			</Popover.Trigger>
			<Popover.Content
				side="right"
				align="end"
				sideOffset={8}
				class="z-50 w-56 rounded-lg border bg-popover p-2 text-popover-foreground shadow-lg"
			>
				<div class="px-2 py-1.5 text-sm">
					<p class="font-medium">{auth.user?.firstName} {auth.user?.lastName}</p>
					<p class="text-xs text-muted-foreground">{auth.user?.email}</p>
				</div>
				<div class="my-1 h-px bg-border"></div>
				<a
					href="/settings"
					class="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors hover:bg-accent hover:text-accent-foreground"
				>
					<Settings class="h-4 w-4" />
					Account Settings
				</a>
				<a
					href="/profile"
					class="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors hover:bg-accent hover:text-accent-foreground"
				>
					<UserCircle class="h-4 w-4" />
					Preferences
				</a>
				<div class="my-1 h-px bg-border"></div>
				<button
					class="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm text-destructive transition-colors hover:bg-accent"
					onclick={() => auth.logout()}
				>
					<LogOut class="h-4 w-4" />
					Log Out
				</button>
			</Popover.Content>
		</Popover.Root>
	</div>
</aside>

// forge/templates/layouts/vue/tabbar/template/src/shared/components/NavRail.vue
<script setup lang="ts">
import type { Component } from 'vue'
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  Sparkles,
  User,
  SlidersHorizontal,
  LogOut,
} from '@lucide/vue'
import { Avatar, AvatarFallback } from '@/shared/ui/avatar'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
} from '@/shared/ui/dropdown-menu'
import { useAuth } from '@/shared/composables/useAuth'

export interface RailItem {
  title: string
  url: string
  icon: Component
}

defineProps<{ items: RailItem[] }>()

const route = useRoute()
const router = useRouter()
const { user, logout } = useAuth()

function isActive(url: string) {
  if (url === '/') return route.path === '/'
  return route.path.startsWith(url)
}

const userInitials = computed(() => {
  if (!user.value) return '?'
  return (
    (user.value.firstName?.[0] ?? '') + (user.value.lastName?.[0] ?? '')
  ).toUpperCase() || user.value.username[0]?.toUpperCase() || '?'
})
</script>

<template>
  <aside
    class="flex h-svh w-[72px] shrink-0 flex-col items-center border-r bg-sidebar-background"
  >
    <!-- Brand mark -->
    <div class="shrink-0 px-2 pt-2">
      <div class="flex h-10 w-14 items-center justify-center">
        <div class="flex h-8 w-8 items-center justify-center rounded-lg ai-gradient">
          <Sparkles class="h-4 w-4 text-white" />
        </div>
      </div>
    </div>

    <!-- Icon-only primary nav -->
    <nav
      class="flex flex-1 flex-col gap-1 overflow-y-auto px-2 pt-2"
      aria-label="Primary navigation"
    >
      <RouterLink
        v-for="item in items"
        :key="item.url"
        :to="item.url"
        :title="item.title"
        :aria-current="isActive(item.url) ? 'page' : undefined"
        class="group relative flex h-10 w-14 items-center justify-center rounded-xl interactive-press focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1"
        :class="isActive(item.url) ? 'bg-primary/10' : 'hover:bg-sidebar-accent'"
      >
        <div
          v-if="isActive(item.url)"
          class="absolute left-0 h-5 w-[3px] rounded-full bg-primary"
        />
        <component
          :is="item.icon"
          class="h-5 w-5"
          :class="isActive(item.url) ? 'text-primary' : 'text-muted-foreground group-hover:text-sidebar-foreground'"
        />
      </RouterLink>
    </nav>

    <!-- User avatar menu at bottom -->
    <div class="shrink-0 border-t border-sidebar-border px-2 py-2">
      <DropdownMenu>
        <DropdownMenuTrigger as-child>
          <button
            class="flex h-12 w-14 items-center justify-center rounded-xl hover:bg-sidebar-accent interactive-press focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1"
            title="Account"
            aria-label="Account menu"
          >
            <Avatar class="h-8 w-8">
              <AvatarFallback class="text-xs">{{ userInitials }}</AvatarFallback>
            </Avatar>
          </button>
        </DropdownMenuTrigger>
        <DropdownMenuContent side="right" align="end" class="w-56">
          <DropdownMenuLabel>My Account</DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuItem @click="router.push('/profile')">
            <User class="mr-2 h-4 w-4" />
            Account Settings
          </DropdownMenuItem>
          <DropdownMenuItem @click="router.push('/settings')">
            <SlidersHorizontal class="mr-2 h-4 w-4" />
            Preferences
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem @click="logout">
            <LogOut class="mr-2 h-4 w-4" />
            Log Out
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  </aside>
</template>
