// forge/templates/apps/vue-frontend-template/template/src/features/ai_chat/ui/AiChatMessage.vue
<script setup lang="ts">
import { ref, computed, nextTick, watch, onBeforeUnmount } from 'vue'
import { Sparkles, Wrench, Copy, Check, Pencil, RefreshCw } from 'lucide-vue-next'
import { marked } from 'marked'
import DOMPurify from 'dompurify'

marked.setOptions({ breaks: true, gfm: true })

// Token-streaming markdown debounce.
//
// Why: each TEXT_MESSAGE_CONTENT delta would otherwise re-parse the entire
// assistant message through marked + DOMPurify and patch a fresh HTML tree
// into the DOM. Typing-rate tokens (~5-20/sec from typical models) thrash
// reconciliation. We collapse bursts into a single render every ~50ms and
// always flush on stream end so the final tokens land within one frame.
const MARKDOWN_DEBOUNCE_MS = 50

function renderMarkdown(text: string): string {
  return DOMPurify.sanitize(marked.parse(text) as string)
}

const props = defineProps<{
  message: { id: string; role: string; content: string }
  isStreaming?: boolean
  /**
   * Show the Regenerate button. Parent decides — typically true only
   * for the LAST assistant message AND when no run is in flight.
   */
  canRegenerate?: boolean
}>()

const emit = defineEmits<{
  edit: [payload: { id: string; content: string }]
  regenerate: [payload: { id: string }]
}>()

const copied = ref(false)
const editing = ref(false)
const editText = ref('')
const editTextarea = ref<HTMLTextAreaElement | null>(null)

// Debounced HTML cache. Raw text remains the source of truth (props.message.content);
// we only debounce the parse-to-HTML step. The cache is updated either after
// MARKDOWN_DEBOUNCE_MS of quiet, or immediately when streaming transitions to
// false (TEXT_MESSAGE_END).
const debouncedHtml = ref(
  props.message.content ? renderMarkdown(props.message.content) : '',
)
let debounceTimer: ReturnType<typeof setTimeout> | null = null

function flushMarkdown() {
  if (debounceTimer !== null) {
    clearTimeout(debounceTimer)
    debounceTimer = null
  }
  debouncedHtml.value = props.message.content
    ? renderMarkdown(props.message.content)
    : ''
}

watch(
  () => props.message.content,
  () => {
    if (!props.isStreaming) {
      // Not streaming: render synchronously (e.g. user edit, replay).
      flushMarkdown()
      return
    }
    if (debounceTimer !== null) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(flushMarkdown, MARKDOWN_DEBOUNCE_MS)
  },
)

// Always render on stream end — the final tokens must appear within frame
// regardless of where the debounce timer was when END arrived.
watch(
  () => props.isStreaming,
  (streaming) => {
    if (!streaming) flushMarkdown()
  },
)

onBeforeUnmount(() => {
  if (debounceTimer !== null) clearTimeout(debounceTimer)
})

const renderedContent = computed(() => debouncedHtml.value)

async function copyMessage() {
  if (!props.message.content) return
  await navigator.clipboard.writeText(props.message.content)
  copied.value = true
  setTimeout(() => { copied.value = false }, 2000)
}

function startEdit() {
  editText.value = props.message.content
  editing.value = true
  nextTick(() => editTextarea.value?.focus())
}

function cancelEdit() {
  editing.value = false
}

function submitEdit() {
  const trimmed = editText.value.trim()
  if (!trimmed) return
  editing.value = false
  emit('edit', { id: props.message.id, content: trimmed })
}
</script>

<template>
  <!-- User message -->
  <div v-if="props.message.role === 'user'" class="group flex justify-end">
    <div class="flex max-w-[80%] flex-col items-end">
      <!-- Action buttons above bubble -->
      <div
        v-if="props.message.content && !editing"
        class="mb-1 flex items-center gap-1 opacity-0 transition-opacity group-hover:opacity-100"
      >
        <button
          class="flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
          :aria-label="copied ? 'Copied' : 'Copy message'"
          @click="copyMessage"
        >
          <Check v-if="copied" class="h-3.5 w-3.5" />
          <Copy v-else class="h-3.5 w-3.5" />
        </button>
        <button
          class="flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
          aria-label="Edit message"
          @click="startEdit"
        >
          <Pencil class="h-3.5 w-3.5" />
        </button>
      </div>
      <!-- Edit mode -->
      <div v-if="editing" class="w-full">
        <textarea
          ref="editTextarea"
          v-model="editText"
          class="w-full resize-none rounded-2xl border bg-muted px-3.5 py-2 text-sm leading-relaxed text-foreground outline-none focus:ring-1 focus:ring-ring"
          rows="3"
          @keydown.enter.exact.prevent="submitEdit"
          @keydown.escape="cancelEdit"
        />
        <div class="mt-1 flex justify-end gap-1.5">
          <button
            class="rounded px-2.5 py-1 text-xs text-muted-foreground hover:bg-accent transition-colors"
            @click="cancelEdit"
          >
            Cancel
          </button>
          <button
            class="rounded bg-primary px-2.5 py-1 text-xs text-primary-foreground hover:bg-primary/90 transition-colors"
            :disabled="!editText.trim()"
            @click="submitEdit"
          >
            Send
          </button>
        </div>
      </div>
      <!-- Display mode -->
      <div
        v-else
        class="rounded-2xl bg-muted px-3.5 py-2 text-sm leading-relaxed text-foreground"
      >
        {{ props.message.content }}
      </div>
    </div>
  </div>

  <!-- Assistant message -->
  <div v-else-if="props.message.role === 'assistant'" class="group flex gap-2.5" role="article" aria-label="Assistant message">
    <div class="flex h-5 w-5 shrink-0 items-center justify-center mt-0.5">
      <Sparkles class="h-4 w-4 text-ai-from" />
    </div>
    <div class="flex min-w-0 flex-1 flex-col gap-1">
      <div
        v-if="props.message.content"
        class="prose prose-sm dark:prose-invert max-w-none text-foreground"
        v-html="renderedContent"
      />
      <div
        v-else-if="props.isStreaming"
        class="text-sm text-muted-foreground animate-pulse"
      >
        Thinking...
      </div>
      <span
        v-if="props.isStreaming && props.message.content"
        class="inline-block w-1.5 h-4 bg-foreground/50 animate-pulse"
      />
      <div
        v-if="props.message.content && !props.isStreaming"
        class="mt-1 flex items-center gap-2 self-start opacity-0 transition-opacity group-hover:opacity-100"
      >
        <button
          class="flex items-center gap-1 text-[10px] text-muted-foreground"
          :aria-label="copied ? 'Copied' : 'Copy message'"
          @click="copyMessage"
        >
          <Check v-if="copied" class="h-3 w-3" />
          <Copy v-else class="h-3 w-3" />
          {{ copied ? 'Copied' : 'Copy' }}
        </button>
        <button
          v-if="props.canRegenerate"
          class="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-foreground transition-colors"
          aria-label="Regenerate response"
          @click="emit('regenerate', { id: props.message.id })"
        >
          <RefreshCw class="h-3 w-3" />
          Regenerate
        </button>
      </div>
    </div>
  </div>

  <!-- Tool message -->
  <div v-else-if="props.message.role === 'tool'" class="flex gap-3">
    <div
      class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted"
    >
      <Wrench class="h-3.5 w-3.5 text-muted-foreground" />
    </div>
    <div class="flex max-w-[80%] flex-col gap-0.5">
      <span class="text-xs font-medium text-muted-foreground">Tool</span>
      <div class="rounded-lg border bg-muted/50 px-3 py-2 text-xs text-muted-foreground">
        {{ props.message.content }}
      </div>
    </div>
  </div>

  <!-- Default / unknown role -->
  <div v-else class="flex gap-3">
    <div class="flex max-w-[80%] flex-col gap-0.5 pl-10">
      <div class="text-sm text-muted-foreground">
        {{ props.message.content }}
      </div>
    </div>
  </div>
</template>

// forge/templates/apps/svelte-frontend-template/template/src/lib/features/chat/ui/AiChatMessage.svelte
<script lang="ts">
	import DOMPurify from 'dompurify';
	import { marked } from 'marked';
	import { Bot, RefreshCw, User } from 'lucide-svelte';
	import type { Message, ToolCallInfo } from '../chat.types';
	import { cn } from '$lib/shared/lib/utils';
	import ToolCallStatus from './ToolCallStatus.svelte';

	let {
		message,
		toolCalls = [],
		onRegenerate,
		isStreaming = false
	}: {
		message: Message;
		toolCalls?: ToolCallInfo[];
		isStreaming?: boolean;
		/**
		 * Show a Regenerate button on this assistant message. Parent
		 * decides — typically only wired on the last assistant message
		 * when no run is in flight.
		 */
		onRegenerate?: (messageId: string) => void;
	} = $props();

	const isAssistant = $derived(message.role !== 'user');

	// Token-streaming markdown debounce.
	//
	// Why: each TEXT_MESSAGE_CONTENT delta would otherwise re-parse the entire
	// assistant message through marked + DOMPurify and patch a fresh HTML tree
	// into the DOM. Typing-rate tokens (~5-20/sec from typical models) thrash
	// reconciliation. We collapse bursts into a single render every ~50ms and
	// always flush on stream end so the final tokens land within one frame.
	const MARKDOWN_DEBOUNCE_MS = 50;

	function renderMarkdown(text: string): string {
		const html = marked.parse(text || '', { async: false }) as string;
		return DOMPurify.sanitize(html);
	}

	// Raw `message.content` remains the source of truth; we debounce only the
	// parse-to-HTML step. `runed` is not a template dep, so we implement the
	// debounce with a `$state` cell and a `setTimeout` driven by `$effect`.
	let renderedHtml = $state(renderMarkdown(message.content || ''));
	let debounceTimer: ReturnType<typeof setTimeout> | null = null;

	function clearTimer() {
		if (debounceTimer !== null) {
			clearTimeout(debounceTimer);
			debounceTimer = null;
		}
	}

	$effect(() => {
		// Track both reactive deps so Svelte 5's runes re-run on either change.
		const raw = message.content || '';
		const streaming = isStreaming;

		clearTimer();
		if (!streaming) {
			// Non-streaming render (initial mount, edit replay, or stream end):
			// flush synchronously so the final tokens appear within one frame.
			renderedHtml = renderMarkdown(raw);
			return;
		}
		debounceTimer = setTimeout(() => {
			renderedHtml = renderMarkdown(raw);
			debounceTimer = null;
		}, MARKDOWN_DEBOUNCE_MS);

		return clearTimer;
	});
</script>

<div
	class={cn('flex gap-3', isAssistant ? '' : 'flex-row-reverse')}
	data-testid="chat-message"
	data-role={message.role}
	data-message-id={message.id}
>
	{#if isAssistant}
		<div
			class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full"
			style="background: linear-gradient(135deg, hsl(var(--ai-gradient-from)), hsl(var(--ai-gradient-to)))"
		>
			<Bot class="h-4 w-4 text-white" />
		</div>
	{:else}
		<div
			class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground"
		>
			<User class="h-4 w-4" />
		</div>
	{/if}

	<div
		class={cn(
			'flex max-w-[85%] flex-col gap-2 rounded-lg px-3 py-2 text-sm leading-[1.6]',
			isAssistant
				? 'bg-ai-surface text-ai-surface-foreground border border-ai-border'
				: 'bg-primary text-primary-foreground'
		)}
	>
		<div class="prose prose-sm dark:prose-invert max-w-none break-words">
			{@html renderedHtml}
		</div>
		{#if isAssistant && toolCalls.length > 0}
			<div class="flex flex-wrap gap-1.5">
				{#each toolCalls as tc (tc.id)}
					<ToolCallStatus toolCall={tc} />
				{/each}
			</div>
		{/if}
		{#if isAssistant && onRegenerate}
			<button
				type="button"
				class="mt-1 flex items-center gap-1 self-start text-[10px] text-muted-foreground hover:text-foreground transition-colors"
				aria-label="Regenerate response"
				data-testid="chat-message-regenerate"
				onclick={() => onRegenerate?.(message.id)}
			>
				<RefreshCw class="h-3 w-3" />
				Regenerate
			</button>
		{/if}
	</div>
</div>
