// forge/templates/apps/svelte-frontend-template/template/src/lib/features/chat/canvas/CanvasFallback.svelte
<script lang="ts">
	import type { WorkspaceActivity } from '../chat.types';

	let { activity }: { activity: WorkspaceActivity } = $props();
</script>

<div class="space-y-2 p-4" data-testid="canvas-fallback">
	<p class="text-sm font-medium">Canvas activity: {activity.activityType}</p>
	<pre
		class="max-h-96 overflow-auto rounded-md bg-muted p-3 font-mono text-xs whitespace-pre-wrap break-all"
	>{JSON.stringify(activity.content, null, 2)}</pre>
</div>

// forge/templates/apps/vue-frontend-template/template/src/features/ai_chat/canvas/CanvasFallback.vue
<script setup lang="ts">
import { Sparkles } from '@lucide/vue'
import type { WorkspaceActivity, AgentState } from '../types'

defineProps<{
  activity: WorkspaceActivity
  state?: AgentState
}>()

defineEmits<{
  action: [action: { type: string; data: Record<string, any> }]
}>()
</script>

<template>
  <div class="flex h-full flex-col items-center justify-center gap-4 p-8 text-center">
    <div class="flex h-16 w-16 items-center justify-center rounded-full bg-muted">
      <Sparkles class="h-8 w-8 text-muted-foreground" />
    </div>
    <div class="space-y-1">
      <p class="text-sm font-medium text-foreground">{{ activity.activityType }}</p>
      <p class="max-w-sm text-xs text-muted-foreground">
        No renderer registered for this activity type.
      </p>
    </div>
    <pre
      v-if="activity.content"
      class="max-h-64 max-w-lg overflow-auto rounded-lg border bg-muted/50 p-3 text-left text-xs"
    >{{ JSON.stringify(activity.content, null, 2) }}</pre>
  </div>
</template>
